"""
FHIR Converter

Converts wearable device data to HL7 FHIR R4 Observation resources.
Maps CSV columns to standards-compliant FHIR resources with LOINC codes.

FHIR Observation Resources:
- Steps → LOINC 41950-7
- Heart Rate → LOINC 8867-4
- Sleep Duration → LOINC 93832-4
- Active Minutes → LOINC 82290-8
- Calories Burned → LOINC 41979-6
- Distance → LOINC 41953-1
"""

from datetime import datetime
from typing import List, Optional

import pandas as pd
from fhir.resources.observation import Observation
from fhir.resources.codeableconcept import CodeableConcept
from fhir.resources.coding import Coding
from fhir.resources.quantity import Quantity
from fhir.resources.reference import Reference
from fhir.resources.annotation import Annotation

from src.utils.constants import (
    LOINC_CODES,
    LOINC_DISPLAY_NAMES,
    UNITS,
    STATUS_FINAL
)
from src.utils.logging_config import setup_logging

logger = setup_logging(__name__)


class FHIRConversionError(Exception):
    """Raised when FHIR conversion fails"""
    pass


def create_observation(
    user_id: int,
    date: str,
    metric_name: str,
    value: float,
    loinc_code: str = None,
    display_name: str = None,
    unit: str = None
) -> Observation:
    """
    Create a FHIR Observation resource for a wearable metric.

    Args:
        user_id: Patient identifier
        date: Observation date (YYYY-MM-DD or datetime)
        metric_name: Metric name (e.g., 'steps', 'heart_rate_avg')
        value: Metric value
        loinc_code: LOINC code (auto-detected if None)
        display_name: Display name (auto-detected if None)
        unit: Unit of measure (auto-detected if None)

    Returns:
        FHIR Observation resource

    Example:
        >>> obs = create_observation(
        ...     user_id=123,
        ...     date='2023-01-01',
        ...     metric_name='steps',
        ...     value=10000
        ... )
        >>> obs.code.coding[0].code  # '41950-7'
    """
    # Auto-detect LOINC code, display name, and unit if not provided
    loinc_code = loinc_code or LOINC_CODES.get(metric_name)
    display_name = display_name or LOINC_DISPLAY_NAMES.get(metric_name, metric_name)
    unit = unit or UNITS.get(metric_name, '')

    if not loinc_code:
        raise FHIRConversionError(
            f"Unknown metric '{metric_name}'. "
            f"Cannot map to LOINC code. "
            f"Known metrics: {list(LOINC_CODES.keys())}"
        )

    # Parse date
    if isinstance(date, str):
        date_obj = pd.to_datetime(date)
    elif isinstance(date, pd.Timestamp):
        date_obj = date.to_pydatetime()
    elif isinstance(date, datetime):
        date_obj = date
    else:
        raise FHIRConversionError(f"Invalid date format: {date}")

    # Create Observation resource
    observation = Observation(
        status=STATUS_FINAL,
        code=CodeableConcept(
            coding=[
                Coding(
                    system="http://loinc.org",
                    code=loinc_code,
                    display=display_name
                )
            ],
            text=display_name
        ),
        subject=Reference(
            reference=f"Patient/{user_id}"
        ),
        effectiveDateTime=str(date_obj.isoformat()),  # Ensure string
        valueQuantity=Quantity(
            value=float(value),
            unit=unit,
            system="http://unitsofmeasure.org",
            code=unit
        ),
        # Educational disclaimer - use Annotation object
        note=[
            Annotation(
                text="Generated by CardioGuard for educational demonstration. "
                     "Not for clinical use."
            )
        ]
    )

    logger.debug(
        f"Created Observation: Patient/{user_id}, "
        f"{metric_name}={value} {unit}, date={date_obj.date()}"
    )

    return observation


def convert_row_to_observations(
    row: pd.Series,
    metrics: List[str] = None
) -> List[Observation]:
    """
    Convert a single data row to multiple FHIR Observation resources.

    Args:
        row: DataFrame row with wearable data
        metrics: List of metric names to convert (default: all known metrics)

    Returns:
        List of FHIR Observation resources

    Example:
        >>> row = df.iloc[0]
        >>> observations = convert_row_to_observations(row)
        >>> len(observations)  # 6 (one per metric)
    """
    metrics = metrics or list(LOINC_CODES.keys())

    observations = []
    user_id = row['user_id']
    date = row['date']

    for metric in metrics:
        if metric not in row or pd.isna(row[metric]):
            logger.debug(f"Skipping missing metric: {metric}")
            continue

        try:
            obs = create_observation(
                user_id=user_id,
                date=date,
                metric_name=metric,
                value=row[metric]
            )
            observations.append(obs)
        except Exception as e:
            logger.warning(f"Failed to create observation for {metric}: {e}")

    return observations


def batch_convert_observations(
    df: pd.DataFrame,
    metrics: List[str] = None
) -> List[Observation]:
    """
    Convert entire DataFrame to FHIR Observation resources.

    Args:
        df: DataFrame with wearable data (must have user_id, date columns)
        metrics: List of metrics to convert (default: all)

    Returns:
        List of all FHIR Observation resources

    Example:
        >>> observations = batch_convert_observations(df)
        >>> print(f"Created {len(observations)} FHIR Observations")
    """
    logger.info(f"Converting {len(df)} rows to FHIR Observations...")

    all_observations = []

    for idx, row in df.iterrows():
        observations = convert_row_to_observations(row, metrics)
        all_observations.extend(observations)

    logger.info(f"Created {len(all_observations)} FHIR Observation resources")

    return all_observations


def observation_to_dict(observation: Observation) -> dict:
    """
    Convert FHIR Observation to dictionary (for JSON serialization).

    Args:
        observation: FHIR Observation resource

    Returns:
        Dictionary representation
    """
    return observation.dict()


def observation_to_json(observation: Observation) -> str:
    """
    Convert FHIR Observation to JSON string.

    Args:
        observation: FHIR Observation resource

    Returns:
        JSON string
    """
    return observation.json(indent=2)


def validate_observation(observation: Observation) -> bool:
    """
    Validate FHIR Observation resource.

    Args:
        observation: FHIR Observation to validate

    Returns:
        True if valid

    Raises:
        FHIRConversionError: If validation fails
    """
    # Basic validation checks
    if not observation.status:
        raise FHIRConversionError("Observation missing status")

    if not observation.code:
        raise FHIRConversionError("Observation missing code")

    if not observation.subject:
        raise FHIRConversionError("Observation missing subject (patient reference)")

    if not observation.effectiveDateTime:
        raise FHIRConversionError("Observation missing effectiveDateTime")

    if not observation.valueQuantity:
        raise FHIRConversionError("Observation missing valueQuantity")

    # Validate LOINC code
    if observation.code.coding:
        loinc_coding = observation.code.coding[0]
        if loinc_coding.system != "http://loinc.org":
            logger.warning(
                f"Expected LOINC system, got: {loinc_coding.system}"
            )

    logger.debug("Observation validation passed")
    return True


# Example usage
if __name__ == "__main__":
    from src.data.ingestion import load_csv

    # Load sample data
    print("Loading sample data...")
    df = load_csv(limit=10)

    print(f"\nLoaded {len(df)} rows\n")

    # Convert single row
    print("=== Single Row Conversion ===")
    row = df.iloc[0]
    observations = convert_row_to_observations(row)

    print(f"Created {len(observations)} observations for patient {row['user_id']} on {row['date']}:")
    for obs in observations:
        loinc = obs.code.coding[0].code
        display = obs.code.coding[0].display
        value = obs.valueQuantity.value
        unit = obs.valueQuantity.unit
        print(f"  - {display} ({loinc}): {value} {unit}")

    # Show JSON for first observation
    print(f"\nSample FHIR Observation JSON:")
    print(observation_to_json(observations[0]))

    # Batch conversion
    print(f"\n=== Batch Conversion ===")
    all_observations = batch_convert_observations(df)
    print(f"Converted {len(df)} rows → {len(all_observations)} FHIR Observations")

    # Validate
    print("\nValidating first observation...")
    validate_observation(observations[0])
    print("✓ Validation passed")
