"""
FHIR Risk Resources

Creates FHIR RiskAssessment and Flag resources for cardiovascular
wellness risk indicators.

Resources:
- RiskAssessment: ML-based risk score with probability and explanations
- Flag: Clinical alerts for medium/high risk patients
"""

from datetime import datetime
from typing import List, Optional, Dict

from fhir.resources.riskassessment import (
    RiskAssessment,
    RiskAssessmentPrediction
)
from fhir.resources.flag import Flag
from fhir.resources.codeableconcept import CodeableConcept
from fhir.resources.coding import Coding
from fhir.resources.reference import Reference
from fhir.resources.period import Period
from fhir.resources.annotation import Annotation

from src.utils.constants import (
    RISK_LEVEL_GREEN,
    RISK_LEVEL_YELLOW,
    RISK_LEVEL_RED,
    FLAG_CATEGORY_CLINICAL,
    STATUS_ACTIVE,
    STATUS_FINAL
)
from src.utils.logging_config import setup_logging

logger = setup_logging(__name__)


class RiskResourceError(Exception):
    """Raised when risk resource creation fails"""
    pass


def create_risk_assessment(
    user_id: int,
    ml_score: float,
    risk_level: str,
    top_features: List[Dict] = None,
    observation_ids: List[str] = None,
    occurrence_date: datetime = None
) -> RiskAssessment:
    """
    Create FHIR RiskAssessment resource from ML prediction.

    Args:
        user_id: Patient identifier
        ml_score: ML risk score (0-1)
        risk_level: Risk level ("Green", "Yellow", "Red")
        top_features: List of top contributing features from SHAP
        observation_ids: List of Observation resource IDs used as basis
        occurrence_date: Assessment date (default: now)

    Returns:
        FHIR RiskAssessment resource

    Example:
        >>> assessment = create_risk_assessment(
        ...     user_id=123,
        ...     ml_score=0.72,
        ...     risk_level="Red",
        ...     top_features=[{'feature_name': 'resting_hr', ...}]
        ... )
    """
    occurrence_date = occurrence_date or datetime.now()
    
    # Convert datetime to ISO string
    occurrence_date_str = occurrence_date.isoformat() if isinstance(occurrence_date, datetime) else str(occurrence_date)

    # Build basis references (Observations used for assessment)
    basis = []
    if observation_ids:
        basis = [
            Reference(reference=f"Observation/{obs_id}")
            for obs_id in observation_ids
        ]

    # Build notes with feature explanations
    notes = _build_risk_notes(top_features)

    # Map risk level to qualitative risk
    qualitative_risk_map = {
        RISK_LEVEL_GREEN: "Low cardiovascular wellness risk",
        RISK_LEVEL_YELLOW: "Medium cardiovascular wellness risk",
        RISK_LEVEL_RED: "High cardiovascular wellness risk"
    }

    risk_assessment = RiskAssessment(
        status=STATUS_FINAL,
        subject=Reference(reference=f"Patient/{user_id}"),
        occurrenceDateTime=occurrence_date_str,  # Use string version
        basis=basis if basis else None,
        prediction=[
            RiskAssessmentPrediction(
                outcome=CodeableConcept(
                    text="Cardiovascular Wellness Risk (Educational)"
                ),
                probabilityDecimal=float(ml_score),
                qualitativeRisk=CodeableConcept(
                    text=qualitative_risk_map.get(
                        risk_level,
                        "Unknown risk level"
                    )
                )
            )
        ],
        note=notes if notes else None,
        # Educational disclaimer
        meta={
            "tag": [{
                "system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
                "code": "HTEST",
                "display": "test health data"
            }]
        }
    )

    logger.debug(
        f"Created RiskAssessment: Patient/{user_id}, "
        f"score={ml_score:.3f}, level={risk_level}"
    )

    return risk_assessment


def _build_risk_notes(top_features: List[Dict] = None) -> List[Annotation]:
    """
    Build notes from SHAP feature explanations.

    Args:
        top_features: List of top contributing features

    Returns:
        List of Annotation objects
    """
    if not top_features:
        return [Annotation(
            text="Risk assessment generated by CardioGuard ML model. "
                 "For educational demonstration only."
        )]

    notes = []

    # Summary note
    feature_summary = "Top contributing factors:\n"
    for i, feature in enumerate(top_features, 1):
        feature_name = feature.get('feature_display_name', feature.get('feature_name'))
        value = feature.get('value')
        unit = feature.get('unit', '')
        impact = feature.get('impact', 'affects')

        feature_summary += (
            f"{i}. {feature_name}: {value:.1f} {unit} "
            f"({impact.lower()} risk)\n"
        )

    notes.append(Annotation(text=feature_summary))

    # Disclaimer
    notes.append(Annotation(
        text="Generated by CardioGuard for educational demonstration. "
             "Not for clinical use. Consult healthcare provider for medical advice."
    ))

    return notes


def create_risk_flag(
    user_id: int,
    risk_level: str,
    reason: str,
    start_date: datetime = None,
    end_date: datetime = None
) -> Optional[Flag]:
    """
    Create FHIR Flag resource for medium/high risk patients.

    Flags are only created for Yellow and Red risk levels.
    Green (low risk) patients do not get flags.

    Args:
        user_id: Patient identifier
        risk_level: Risk level ("Green", "Yellow", "Red")
        reason: Reason for flag (e.g., "Elevated resting heart rate")
        start_date: Flag start date (default: now)
        end_date: Flag end date (optional, ongoing if None)

    Returns:
        FHIR Flag resource, or None if risk is Green

    Example:
        >>> flag = create_risk_flag(
        ...     user_id=123,
        ...     risk_level="Red",
        ...     reason="Multiple cardiovascular wellness indicators warrant attention"
        ... )
    """
    # No flag for low risk
    if risk_level == RISK_LEVEL_GREEN:
        logger.debug(f"Patient {user_id}: Low risk, no flag created")
        return None

    start_date = start_date or datetime.now()
    
    # Convert dates to ISO strings
    start_date_str = start_date.isoformat() if isinstance(start_date, datetime) else str(start_date)
    end_date_str = end_date.isoformat() if isinstance(end_date, datetime) else str(end_date) if end_date else None

    # Build period
    period_dict = {"start": start_date_str}
    if end_date_str:
        period_dict["end"] = end_date_str

    period = Period(**period_dict)

    # Priority based on risk level
    priority_map = {
        RISK_LEVEL_YELLOW: "medium",
        RISK_LEVEL_RED: "high"
    }
    priority = priority_map.get(risk_level, "medium")

    flag = Flag(
        status=STATUS_ACTIVE,
        category=[
            CodeableConcept(
                coding=[
                    Coding(
                        system="http://terminology.hl7.org/CodeSystem/flag-category",
                        code=FLAG_CATEGORY_CLINICAL,
                        display="Clinical"
                    )
                ]
            )
        ],
        code=CodeableConcept(
            text=f"Cardiovascular Wellness Risk: {risk_level}"
        ),
        subject=Reference(reference=f"Patient/{user_id}"),
        period=period,
        # Note: FHIR R4 doesn't have priority field directly,
        # we include it in the code text
        # Educational disclaimer
        meta={
            "tag": [{
                "system": "http://terminology.hl7.org/CodeSystem/v3-ActReason",
                "code": "HTEST",
                "display": "test health data"
            }]
        }
    )

    logger.debug(
        f"Created Flag: Patient/{user_id}, "
        f"risk={risk_level}, reason={reason}"
    )

    return flag


def risk_assessment_to_json(risk_assessment: RiskAssessment) -> str:
    """Convert RiskAssessment to JSON string."""
    return risk_assessment.json(indent=2)


def flag_to_json(flag: Flag) -> str:
    """Convert Flag to JSON string."""
    return flag.json(indent=2)


# Example usage
if __name__ == "__main__":
    # Sample SHAP features
    sample_features = [
        {
            'feature_name': 'resting_hr_estimate',
            'feature_display_name': 'Resting Heart Rate',
            'value': 92.5,
            'unit': 'bpm',
            'impact': 'INCREASES',
            'shap_value': 0.25
        },
        {
            'feature_name': 'sleep_hours_avg',
            'feature_display_name': 'Average Sleep Duration',
            'value': 5.2,
            'unit': 'hours',
            'impact': 'INCREASES',
            'shap_value': 0.18
        },
        {
            'feature_name': 'activity_score',
            'feature_display_name': 'Physical Activity Score',
            'value': 18.5,
            'unit': 'points',
            'impact': 'INCREASES',
            'shap_value': 0.15
        }
    ]

    # Sample observation IDs
    obs_ids = ['obs-123', 'obs-124', 'obs-125']

    print("=== Creating FHIR RiskAssessment ===\n")

    # Create RiskAssessment
    risk_assessment = create_risk_assessment(
        user_id=123,
        ml_score=0.72,
        risk_level=RISK_LEVEL_RED,
        top_features=sample_features,
        observation_ids=obs_ids
    )

    print("RiskAssessment created:")
    print(f"  Patient: {risk_assessment.subject.reference}")
    print(f"  Probability: {risk_assessment.prediction[0].probabilityDecimal}")
    print(f"  Risk: {risk_assessment.prediction[0].qualitativeRisk.text}")
    print(f"  Basis: {len(risk_assessment.basis)} observations" if risk_assessment.basis else "  No basis observations")
    print(f"  Notes: {len(risk_assessment.note)}" if risk_assessment.note else "  No notes")

    print(f"\nRiskAssessment JSON:")
    print(risk_assessment_to_json(risk_assessment))

    print("\n" + "="*60)
    print("=== Creating FHIR Flag ===\n")

    # Create Flag
    flag = create_risk_flag(
        user_id=123,
        risk_level=RISK_LEVEL_RED,
        reason="Multiple cardiovascular wellness indicators warrant attention"
    )

    if flag:
        print("Flag created:")
        print(f"  Patient: {flag.subject.reference}")
        print(f"  Code: {flag.code.text}")
        print(f"  Status: {flag.status}")
        print(f"  Category: {flag.category[0].coding[0].display}")

        print(f"\nFlag JSON:")
        print(flag_to_json(flag))
    else:
        print("No flag created (low risk)")

    # Test Green risk (no flag)
    print("\n" + "="*60)
    print("=== Testing Green Risk (No Flag) ===\n")

    flag_green = create_risk_flag(
        user_id=456,
        risk_level=RISK_LEVEL_GREEN,
        reason="Low risk"
    )

    if flag_green:
        print("Flag created (unexpected)")
    else:
        print("✓ No flag created for low risk patient (as expected)")
